from .ac import AcResource
from .floor_lamp import FloorLampResource
from .lava_lamp import LavaLampResource
from .led_strip import LedStripResource
from .lights import LightsResource
from .pc import PCResource
from .pc_lamp import PCLampResource
from .salt_lamp import SaltLampResource
from .tv import TvResource
